version: "2.15.1"

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yw_web
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
  yw-web-service:
    build: .
    ports:
      - 80:8080
    restart: on-failure
    environment:
      YW_WEB_DB_CONNECTION_URI: "jdbc:mysql://db:3306/yw_web"
    depends_on:
      - db