spring:
  datasource:
    url: ${YW_WEB_DB_CONNECTION_URI:jdbc:mysql://localhost:3306/yw_web}
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false